version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ci_mysql_db
    environment:
      MYSQL_DATABASE: golf_db
      MYSQL_USER: golfuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
