version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ci_mysql_db
    environment:
      MYSQL_DATABASE: golf_db
      MYSQL_USER: golfuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  golf-club-api:
    build: .
    container_name: golf-club-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golf_db
      SPRING_DATASOURCE_USERNAME: golfuser
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  db_data: