name: Golf API CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Check out code
        uses: actions/checkout@v2

      # 2) Set up Java 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Cache Maven Packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 4) Build with Maven
      - name: Build with Maven
        run: |
          mvn clean install --batch-mode

      # 5) Run tests
      - name: Run tests
        run: |
          mvn test --batch-mode
