name: Golf API CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # 2) Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Set up Docker Buildx
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Build containers
      - name: Docker compose build
        run: docker compose build

      # 5) Start containers in detached mode
      - name: Docker compose up
        run: docker compose up -d

      # 6) Wait for MySQL
      - name: Wait for MySQL
        run: |
          # Try up to 30 seconds (15 tries * 2s)
          for i in {1..15}; do
            # Exec into the container "ci_mysql_db" and ping MySQL
            if docker exec ci_mysql_db mysqladmin ping -ugolfuser -ppassword --silent; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "MySQL not ready, waiting..."
            sleep 2
          done
          echo "MySQL did not become ready in time."
          exit 1

      # 7) Maven build & test
      - name: Maven build and test
        run: mvn clean test